# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /posts/:title
timezone: America/Sao_Paulo

# Setup
title: Carlos Alexandro Becker
tagline: ''
description: 'Thougths, tutorials and hacks by Carlos Alexandro Becker.'
url: http://carlosbecker.com
tracking_code: 'UA-50435491-1'

author:
  name: 'Carlos Alexandro Becker'
  url: https://twitter.com/caarlos0

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  sass_dir: _scss
  style: :compressed

paginate: 10

# Custom vars
disqus_shortname: caarlos0blog

