# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: /posts/:title

# Setup
title: Carlos Alexandro Becker
tagline: ''
description: 'Thougths, tutorials and hacks by Carlos Alexandro Becker.'
url: http://carlosbecker.com
tracking_code: 'UA-50435491-1'

author:
  name: 'Carlos Alexandro Becker'
  url: https://twitter.com/caarlos0

exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5

# Custom vars
disqus_shortname: caarlos0blog

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
