# Dependencies
highlighter: rouge

# Permalinks
permalink: /posts/:title
timezone: America/Austin

# Setup
title: Soheil Salehian
description: 'My adventures of building distributed artificial intelligence systems, by Soheil Salehian'
baseurl:     ''
url:         'http://soheilsalehian.github.com'

author:
  name: 'Soheil Salehian'
  url: https://angel.co/soheil-salehian
  email: soheil.salehian@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
sass:
  sass_dir: _scss
  compressed: true

paginate: 3

# Custom vars
show_related_posts: true
animated: true

# Social icons
show_social_icons: true
github_username: soheilsalehian
linkedin_username: soheilsalehian
angellist_username: soheil-salehian
